Se posts my posts
nss-day-cohort-43-csharp/Fullstack-Panteras-Implicit-Return pull request #61
Opened 2021-01-20 20:20 UTC by ste163

# Description
Users can go to a new url, /myposts, to see a list of all of their posts in descending order. The post list includes those that have not been approved.

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
# Testing Instructions
1. Sign in with a user WITH posts
2. Go to My Posts section from the new Nav Bar link
3. You should see a list of ALL of that users post regardless of whether or not they have been approved
4. Sign in with a user WITHOUT posts
5. Go to My Posts
6. You should see a message saying you don't have posts.
# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

2021-01-20 20:54 UTC, terraroush approved these changes
it does all the things you say! well done!

2021-01-23 16:59 UTC, terraroush requested changes
i should be getting a list of posts back on myPosts, but it's saying "you don't have any posts"

2021-01-23 17:20 UTC, terraroush approved these changes

2021-01-25 17:36 UTC, tristan0508 approved these changes
Looks good

2021-01-25 17:39 UTC, merged